config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from prm.dashboard.views import DashboardRedirectView
from prm.users.views import UserSignupView

urlpatterns = [
    path("", DashboardRedirectView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("accounts/signup/", UserSignupView.as_view(), name="account_signup"),
    path("accounts/", include("allauth.urls")),
    # Apps
    path("dashboard/", include("prm.dashboard.urls", namespace="dashboard")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

prm/dashboard/urls.py
from django.urls import path

from .apps import DashboardConfig
from .views import (
    AvatarUpdateView,
    DashboardIndexView,
    DashboardProfileView,
    DashboardRedirectView,
    DashboardTeamView,
    DashboardTokenView,
    PollToken,
    PollUserBalance,
    PollUserTransactions,
    metamask_confirm,
)

app_name = DashboardConfig.label

urlpatterns = [
    path("", view=DashboardRedirectView.as_view(), name="home_redirect"),
    path("~redirect/", view=DashboardRedirectView.as_view(), name="redirect"),
    path("~avatar-update/", AvatarUpdateView.as_view(), name="avatar_update"),
    path("~metamask-confirm/", metamask_confirm, name="metamask_confirm"),
    # Polling views
    path("poll-active-round/", PollToken.as_view(), name="poll_active_round"),
    path("poll-token-rounds/", PollToken.as_view(), name="poll_token_rounds"),
    path("poll-user-balance/", PollUserBalance.as_view(), name="poll_user_balance"),
    path(
        "poll-user-transactions/",
        PollUserTransactions.as_view(),
        name="poll_user_transactions",
    ),
    # Generic views
    path("<str:username>/", DashboardIndexView.as_view(), name="index"),
    path("<str:username>/token/", DashboardTokenView.as_view(), name="token"),
    path("<str:username>/team/", DashboardTeamView.as_view(), name="team"),
    path("<str:username>/profile/", DashboardProfileView.as_view(), name="profile"),
]

prm/dashboard/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.utils.translation import gettext_lazy as _

from .validators import (
    validate_available_tokens,
    validate_image_max_pixel_size,
    validate_image_min_pixel_size,
    validate_image_size,
)

User = get_user_model()


class BuyTokenForm(forms.Form):
    token_price_usd = forms.CharField(
        label=" ",
        widget=forms.TextInput(attrs={"placeholder": _("Введите сумму USDT")}),
        required=False,
        validators=[
            validate_available_tokens,
        ],
    )
    token_amount = forms.CharField(
        label=" ",
        widget=forms.TextInput(
            attrs={"placeholder": _("Вы получите:"), "readonly": "readonly"}
        ),
    )

    def clean_token_amount(self):
        token_amount = self.cleaned_data.get("token_amount", None)
        if token_amount <= 0:
            raise forms.ValidationError(_("Неверное количество."))
        return token_amount


class AvatarUpdateForm(forms.Form):
    avatar = forms.ImageField(
        required=False,
        validators=[
            validate_image_size,
            validate_image_min_pixel_size,
            validate_image_max_pixel_size,
        ],
    )

    def clean_avatar(self):
        avatar = self.cleaned_data.get("avatar", None)
        if not avatar:
            raise forms.ValidationError(_("Avatar is required."))
        return avatar


class ProfileUserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "email",
            "birthday",
            "city",
            "metamask_wallet",
            # don't add password/password1 here
        ]

    city = forms.CharField(label=_("Город"), required=False)
    birthday = forms.DateField(
        label=_("Дата рождения"),
        required=False,
        widget=forms.TextInput(attrs={"type": "date"}),
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        required=False,
    )
    password1 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        required=False,
    )

    def clean_password(self):
        """
        Validate that the password is as per the required password policy.
        """
        password = self.cleaned_data.get("password")
        if password:
            password_validation.validate_password(password)
        return password

    def clean_password1(self):
        """
        Validate that the two password inputs match.
        """
        password1 = self.cleaned_data.get("password1")
        password = self.cleaned_data.get("password")
        if password and password1 and password != password1:
            raise forms.ValidationError(_("Passwords do not match"))
        return password1

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["city"].initial = self.instance.settings.city
        self.fields["birthday"].initial = self.instance.settings.birthday

    def save(self, commit=True):
        """
        Save the updated user information and the new password (if entered).
        """
        user = super().save(commit=False)
        password = self.cleaned_data.get("password")
        user.settings.city = self.cleaned_data["city"]
        user.settings.birthday = self.cleaned_data["birthday"]

        if password:
            user.set_password(password)

        if commit:
            user.settings.save()
            user.save()

        return user

prm/dashboard/views.py
import json

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.cache import cache
from django.core.paginator import EmptyPage, InvalidPage, Paginator
from django.http import Http404, HttpResponseNotAllowed, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import RedirectView, TemplateView, UpdateView, View

from prm.core.services import CacheService, MetamaskService
from prm.users.services import recalculate_user_balance, set_parent_in_smart

from .forms import AvatarUpdateForm, BuyTokenForm, ProfileUserUpdateForm

User = get_user_model()


def metamask_confirm(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            user = get_object_or_404(User, username=data.get("user"))
            account_address = data.get("accountAddress")
            signature = data.get("signature")
            csrf_token = data.get("csrf_token")
            # verify signature
            is_valid_signature = MetamaskService.verify_signature(
                account_address=account_address,
                signature=signature,
                original_message=csrf_token,
            )
            if not is_valid_signature:
                return JsonResponse({"error": "Invalid signature"}, status=400)
            # update user metamask data
            MetamaskService.confirm_user_wallet(
                user=user, account_address=account_address
            )

            if user.parent:
                set_parent_in_smart(user)
            recalculate_user_balance(user)
        except Exception as e:
            return JsonResponse({"message": "Error", "exception": str(e)}, status=500)
        return JsonResponse({"message": "Success"}, status=201)
    return HttpResponseNotAllowed(["POST"])


class PollToken(LoginRequiredMixin, TemplateView):
    def get_context_data(self, *args, **kwargs):
        token = CacheService.get_token()
        token_active_round = CacheService.get_token_active_round()
        token_rounds = CacheService.get_token_rounds()
        return {
            "token": token,
            "token_active_round": token_active_round,
            "token_rounds": token_rounds,
        }

    def get(self, request, *args, **kwargs):
        template_name = "dashboard/components/token_active_round.html"
        if request.path == reverse_lazy("dashboard:poll_token_rounds"):
            template_name = "dashboard/components/token_rounds.html"
        context = self.get_context_data()
        return render(request, template_name, context)


class PollUserBalance(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/components/user_balance.html"

    def get_context_data(self, *args, **kwargs):
        user = self.request.user
        token = CacheService.get_token()
        token_active_round = CacheService.get_token_active_round()
        user_balance = CacheService.get_user_balance(user, token)
        return {
            "user": user,
            "user_balance": user_balance,
            "token": token,
            "token_active_round": token_active_round,
        }


class PollUserTransactions(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/components/transaction_history.html"

    def get_context_data(self, *args, **kwargs):
        transactions = CacheService.get_user_transactions(self.request.user)
        return {"user_transactions": transactions}


class DashboardRedirectView(RedirectView):
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return reverse_lazy(
                "dashboard:index", kwargs={"username": self.request.user.username}
            )
        return reverse_lazy("account_login")


class DashboardBaseView(LoginRequiredMixin, View):
    template_name = ""
    default_limit = 10
    default_page = 1
    max_limit = 50

    def get_context_data(self):
        token = CacheService.get_token()
        token_rounds = CacheService.get_token_rounds()
        token_active_round = cache.get("token_active_round")
        user = self.request.user
        user_referral = self.request.build_absolute_uri(
            reverse_lazy("account_signup") + "?referral=" + user.username
        )
        user_balance = CacheService.get_user_balance(user, token)
        user_children = CacheService.get_user_children(user)
        user_transactions = CacheService.get_user_transactions(user)

        # Children pagination
        user_children = Paginator(
            user_children, self.request.COOKIES.get("children_size", self.default_limit)
        ).page(self.request.GET.get("c_page", self.default_page))
        user_children_page_range = user_children.paginator.get_elided_page_range(
            self.request.GET.get("c_page", self.default_page), on_each_side=3, on_ends=1
        )
        # Transactions pagination
        user_transactions = Paginator(
            user_transactions,
            self.request.COOKIES.get("transactions_size", self.default_limit),
        ).page(self.request.GET.get("t_page", self.default_page))
        user_transactions_page_range = (
            user_transactions.paginator.get_elided_page_range(
                self.request.GET.get("t_page", self.default_page),
                on_each_side=3,
                on_ends=1,
            )
        )

        return {
            "user": user,
            "user_referral_link": user_referral,
            "user_balance": user_balance,
            "user_children": user_children,
            "user_children_page_range": user_children_page_range,
            "user_transactions": user_transactions,
            "user_transactions_page_range": user_transactions_page_range,
            "token": token,
            "token_rounds": token_rounds,
            "token_active_round": token_active_round,
            "page_sizes": [10, 25, 50],
        }

    def get(self, request, *args, **kwargs):
        try:
            context = self.get_context_data()
        except (EmptyPage, InvalidPage):
            raise Http404()
        return render(request, self.template_name, context)


class DashboardIndexView(DashboardBaseView):
    template_name = "dashboard/index.html"


class DashboardTokenView(DashboardBaseView):
    template_name = "dashboard/token.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        context["buy_token_form"] = BuyTokenForm()
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = BuyTokenForm(request.POST)
        if form.is_valid():
            user = self.request.user
            return redirect(
                reverse_lazy("dashboard:token", kwargs={"username": user.username})
            )
        context = self.get_context_data()
        context["buy_token_form"] = form
        return render(request, self.template_name, context)


class DashboardTeamView(DashboardBaseView):
    template_name = "dashboard/team.html"


class DashboardProfileView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = ProfileUserUpdateForm
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "dashboard/profile.html"
    success_message = _("Информация успешно обновлена")

    def get_success_url(self):
        return reverse_lazy(
            "dashboard:profile", kwargs={"username": self.request.user.username}
        )

    def get_object(self, *args, **kwargs):
        return self.request.user


class AvatarUpdateView(LoginRequiredMixin, View):
    def post(self, request):
        form = AvatarUpdateForm(request.POST, request.FILES)
        if form.is_valid() and request.FILES:
            user = self.request.user
            user.avatar = form.cleaned_data.get("avatar")
            user.save()
            return JsonResponse({"avatar_url": user.avatar.url})
        # handle form errors
        errors = form.errors.as_data()
        error_messages = [
            error.message for error_list in errors.values() for error in error_list
        ]
        return JsonResponse({"error": error_messages}, status=400)

prm/users/views.py
from allauth.account.views import SignupView

from .forms import UserSignupForm


class UserSignupView(SignupView):
    form_class = UserSignupForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

prm/templates/dashboard/components/token_active_round.html
{% load static %}
{% load humanize %}
{% load l10n %}
{% load i18n %}
{% load dashboard_extras %}

<div id="token_active_round" class="round_content"
    {% if HTMX_ALLOW_POLLING %}
    hx-get="{% url 'dashboard:poll_active_round' %}"
    hx-trigger="every 10s"
    hx-swap="outerHTML"
    {% endif %}>
    <div class="table">
        <p class="description">{% translate "Раунд" %}</p>
        <p class="description">{% translate "Цена" %}</p>
        <p class="description">{% translate "Осталось токенов" %}</p>
        <p class="description">{% translate "Прогресс" %}</p>

        <div class="round_number">
            <img src="{% static 'img/icons/checkbox_active.svg'%}" alt="checkbox_active">
            <p class="round_percent">
                {{ token_active_round.name }}
                {{ token_active_round.percent_share }}%
            </p>
        </div>
        <p class="price">
            {{ token_active_round.currency }}
            {{ token_active_round.unit_price|strip_zeros|unlocalize }}
        </p>
        <p class="total_cost">
            {{ token_active_round.available_amount|intcomma }}
        </p>
        <div class="progress-container">
            <div class="progress-bar">
                <div class="progress" style="width: {{ token_active_round.progress|unlocalize }}%"></div>
                <div class="bar_delimeters">
                    <div class="bar_delimeter bar_delimeter_25 "></div>
                    <div class="bar_delimeter bar_delimeter_50 "></div>
                    <div class="bar_delimeter bar_delimeter_75 "></div>
                </div >
            </div>
        </div>
    </div>
</div >

prm/templates/dashboard/components/token_round.html
{% load static %}
{% load humanize %}
{% load l10n %}
{% load i18n %}
{% load dashboard_extras %}

<div id="active_round" class="round_content"
    hx-get="{% url 'dashboard:update_index_content' %}"
    hx-trigger="every 2s"
    hx-swap="outerHTML">
    <div class="table">
        <p class="description">{% translate "Раунд" %}</p>
        <p class="description">{% translate "Цена" %}</p>
        <p class="description">{% translate "Осталось токенов" %}</p>

        <div class="round_number">
            <img src="{% static 'img/icons/checkbox_active.svg'%}" alt="checkbox_active">
            <p class="round_percent">
                {{ token.active_round.name }}
                {{ token.active_round.percent_share }}%
            </p>
        </div>
        <p class="price">
            {{ token.active_round.currency }}
            {{ token.active_round.unit_price|strip_zeros|unlocalize }}
        </p>
        <p class="total_cost">
            {{ token.active_round.available_amount|intcomma }}
        </p>
    </div>
</div >

prm/templates/dashboard/components/token_rounds.html
{% load static %}
{% load l10n %}
{% load i18n %}
{% load humanize %}
{% load dashboard_extras %}

<div id="round" class="tile big_tile"
    {% if HTMX_ALLOW_POLLING %}
    hx-get="{% url 'dashboard:poll_token_rounds' %}"
    hx-trigger="every 10s"
    hx-swap="outerHTML"
    {% endif %}>
    <h3 class="big_name">{% translate "Раунды продаж" %}</h3>
    <div class="round_content">
        <div class="table">
            <p class="description">{% translate "Раунд" %}</p>
            <p class="description">{% translate "Цена" %}</p>
            <p class="description">{% translate "Полная стоимость" %}</p>
            <p class="description">{% translate "Прогресс" %}</p>

            {% for token_round in token_rounds %}
                <div class="round_number">
                    {% if token_active_round == token_round %}
                    <img src="{% static 'img/icons/checkbox_active.svg'%}" alt="checkbox_active">
                    {% else %}
                    <img src="{% static 'img/icons/checkbox.svg'%}" alt="checkbox">
                    {% endif %}
                    <p class="round_percent">
                        {{ token_round.name }} {{ token_round.percent_share }}%
                    </p>
                </div>
                <p class="price">{{ token_round.currency }} {{ token_round.unit_price|strip_zeros|unlocalize }}</p>
                <p class="total_cost">{{ token_round.currency }} {{ token_round.total_cost|intcomma }}</p>
                <div class="progress-container">
                    <div class="progress-bar">
                        <div class="progress" style="width: {{ token_round.progress|unlocalize }}%"></div>
                        <div class="bar_delimeters">
                            <div class="bar_delimeter bar_delimeter_25 "></div>
                            <div class="bar_delimeter bar_delimeter_50 "></div>
                            <div class="bar_delimeter bar_delimeter_75 "></div>
                        </div >
                    </div>
                </div>
            {% endfor %}

        </div>
        {% comment %} <img class="diagram" src="{% static 'img/icons/diagram.svg'%}" alt=""> {% endcomment %}
    </div >
</div>

prm/templates/dashboard/components/transaction_history.html
{% load humanize %}
{% load i18n %}

<section class="tile tile-lg"
    {% if HTMX_ALLOW_POLLING %}
    hx-get="{% url 'dashboard:poll_user_transactions' %}"
    hx-trigger="every 30s"
    hx-swap="outerHTML"
    {% endif %}>
    <h2 class="big_name">{% translate "История начислений" %}</h2>
    <div class="flexible-table">
        <div class="row row-header">
            <div class="cell">{% translate "От кого" %}</div>
            <div class="cell">{% translate "Тип" %}</div>
            <div class="cell">{% translate "Кол-во токенов" %}</div>
            <div class="cell">{% translate "Дата начисления" %}</div>
        </div>
        {% for transaction in user_transactions %}
            <div class="row">
                <div class="cell">{{ transaction.buyer.username }}</div>
                {% if transaction.reward_type == "admin" %}
                    <div class="cell">{% translate "начисление от сервиса" %}</div>
                    <div class="cell">{{ transaction.reward|intcomma }}</div>
                {% else %}
                    {% if transaction.reward and transaction.buyer.username != user.username %}
                        <div class="cell">{% translate "бонус 5%" %}</div>
                        <div class="cell">{{ transaction.reward|intcomma }}</div>
                    {% else %}
                        <div class="cell">{% translate "покупка" %}</div>
                        <div class="cell">{{ transaction.amount|intcomma }}</div>
                    {% endif %}
                {% endif %}
                <div class="cell">{{ transaction.created_at|date:"d.b.Y" }}</div>
            </div>
        {% endfor %}
    </div>
    <div class="pages">
        <select id="transactions_size" class="page_amount_selector">
            {% for amount in page_sizes %}
                <option value="{{ amount }}" {% if amount == user_transactions.paginator.per_page %}selected{% endif %}>
                    Показывать по {{ amount }} записей
                </option>
            {% endfor %}
        </select>
        <ul class="pagination">
            {% if user_transactions.has_previous %}
                <li>
                    <a class="page_btn" href="?page={{ user_transactions.previous_page_number }}">
                        &lt;
                    </a>
                </li>
                {% else %}
                <li><span class="page_btn" disabled>&lt;</span></li>
            {% endif %}
            {% for page_num in user_transactions_page_range %}
                {% if page_num == user_transactions.number %}
                    <li><span class="page_btn active_page">{{ page_num }}</li>
                {% elif page_num == user_transactions.paginator.ELLIPSIS %}
                    <li><span class="page_btn">{{ page_num }}</li>
                {% else %}
                    <li><a class="page_btn" href="?t_page={{ page_num }}">{{ page_num }}</a></li>
                {% endif %}
            {% endfor %}

            {% if user_transactions.has_next %}
                <li>
                    <a class="page_btn" href="?t_page={{ user_transactions.next_page_number }}">
                        &gt;
                    </a>
                </li>
                {% else %}
                <li><span class="page_btn">&gt;</span></li>
            {% endif %}
        </ul>
    </div>
</section>

prm/templates/dashboard/components/user_balance.html
{% load static %}
{% load l10n %}
{% load i18n %}
{% load humanize %}
{% load dashboard_extras %}

<div class="tiles"
    {% if HTMX_ALLOW_POLLING %}
    hx-get="{% url 'dashboard:poll_user_balance' %}"
    hx-trigger="every 10s"
    hx-swap="outerHTML"
    {% endif %}>
    <div id="my_tokens" class="tile little_tile">
        <img class="tile_icon" src="{% static 'img/icons/my_tokens_icon.svg'%}" alt="">
        <div class="tile_text">
            <p class="tile_name">{% translate "Мои токены" %}</p>
            <p class="tile_counter">{{ user.token_balance|intcomma }}</p>
        </div>
    </div>
    <div id="token_sum" class="tile little_tile">
        <img class="tile_icon" src="{% static 'img/icons/sum_icon.svg'%}" alt="">
        <div class="tile_text">
            <p class="tile_name">{% translate "Сумма токенов" %}</p>
            <p class="tile_counter">$ {{ user_balance|unlocalize }}</p>
        </div>
    </div>
    <div id="token_amount" class="tile little_tile">
        <img class="tile_icon" src="" alt="">
        <div class="tile_text">
            <p class="tile_name">{% translate "Кол-во токенов в продаже" %}</p>
            <p class="tile_counter">{{ token.available_to_sale|intcomma }}</p>
        </div>
    </div>
    <div id="rate" class="tile little_tile">
        <img class="tile_icon" src="{% static 'img/icons/rate_icon.svg'%}" alt="">
        <div class="tile_text">
            <p class="tile_name">{% translate "Курс 1 PRM токена " %}</p>
            <p class="tile_counter">
                {% comment %} <span>1 PRM =</span> {% endcomment %}
                <span>
                    {{ token_active_round.currency }}
                    {{ token_active_round.unit_price|strip_zeros|unlocalize }}
                </span>
            </p>
        </div>
    </div>
</div>