config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views

from prm.dashboard.views import DashboardRedirectView
from prm.users.views import UserSignupView

urlpatterns = [
    path("", DashboardRedirectView.as_view(), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("accounts/signup/", UserSignupView.as_view(), name="account_signup"),
    path("accounts/", include("allauth.urls")),
    # Apps
    path("dashboard/", include("prm.dashboard.urls", namespace="dashboard")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

prm/dashboard/urls.py
from django.urls import path

from .apps import DashboardConfig
from .views import (
    AvatarUpdateView,
    DashboardIndexView,
    DashboardProfileView,
    DashboardRedirectView,
    DashboardTeamView,
    DashboardTokenView,
    PollToken,
    PollUserBalance,
    PollUserTransactions,
    metamask_confirm,
)

app_name = DashboardConfig.label

urlpatterns = [
    path("", view=DashboardRedirectView.as_view(), name="home_redirect"),
    path("~redirect/", view=DashboardRedirectView.as_view(), name="redirect"),
    path("~avatar-update/", AvatarUpdateView.as_view(), name="avatar_update"),
    path("~metamask-confirm/", metamask_confirm, name="metamask_confirm"),
    # Polling views
    path("poll-active-round/", PollToken.as_view(), name="poll_active_round"),
    path("poll-token-rounds/", PollToken.as_view(), name="poll_token_rounds"),
    path("poll-user-balance/", PollUserBalance.as_view(), name="poll_user_balance"),
    path(
        "poll-user-transactions/",
        PollUserTransactions.as_view(),
        name="poll_user_transactions",
    ),
    # Generic views
    path("<str:username>/", DashboardIndexView.as_view(), name="index"),
    path("<str:username>/token/", DashboardTokenView.as_view(), name="token"),
    path("<str:username>/team/", DashboardTeamView.as_view(), name="team"),
    path("<str:username>/profile/", DashboardProfileView.as_view(), name="profile"),
]

prm/dashboard/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.utils.translation import gettext_lazy as _

from .validators import (
    validate_available_tokens,
    validate_image_max_pixel_size,
    validate_image_min_pixel_size,
    validate_image_size,
)

User = get_user_model()


class BuyTokenForm(forms.Form):
    token_price_usd = forms.CharField(
        label=" ",
        widget=forms.TextInput(attrs={"placeholder": _("Введите сумму USDT")}),
        required=False,
        validators=[
            validate_available_tokens,
        ],
    )
    token_amount = forms.CharField(
        label=" ",
        widget=forms.TextInput(
            attrs={"placeholder": _("Вы получите:"), "readonly": "readonly"}
        ),
    )

    def clean_token_amount(self):
        token_amount = self.cleaned_data.get("token_amount", None)
        if token_amount <= 0:
            raise forms.ValidationError(_("Неверное количество."))
        return token_amount


class AvatarUpdateForm(forms.Form):
    avatar = forms.ImageField(
        required=False,
        validators=[
            validate_image_size,
            validate_image_min_pixel_size,
            validate_image_max_pixel_size,
        ],
    )

    def clean_avatar(self):
        avatar = self.cleaned_data.get("avatar", None)
        if not avatar:
            raise forms.ValidationError(_("Avatar is required."))
        return avatar


class ProfileUserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "email",
            "birthday",
            "city",
            "metamask_wallet",
            # don't add password/password1 here
        ]

    city = forms.CharField(label=_("Город"), required=False)
    birthday = forms.DateField(
        label=_("Дата рождения"),
        required=False,
        widget=forms.TextInput(attrs={"type": "date"}),
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        required=False,
    )
    password1 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        required=False,
    )

    def clean_password(self):
        """
        Validate that the password is as per the required password policy.
        """
        password = self.cleaned_data.get("password")
        if password:
            password_validation.validate_password(password)
        return password

    def clean_password1(self):
        """
        Validate that the two password inputs match.
        """
        password1 = self.cleaned_data.get("password1")
        password = self.cleaned_data.get("password")
        if password and password1 and password != password1:
            raise forms.ValidationError(_("Passwords do not match"))
        return password1

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["city"].initial = self.instance.settings.city
        self.fields["birthday"].initial = self.instance.settings.birthday

    def save(self, commit=True):
        """
        Save the updated user information and the new password (if entered).
        """
        user = super().save(commit=False)
        password = self.cleaned_data.get("password")
        user.settings.city = self.cleaned_data["city"]
        user.settings.birthday = self.cleaned_data["birthday"]

        if password:
            user.set_password(password)

        if commit:
            user.settings.save()
            user.save()

        return user

prm/dashboard/views.py
import json

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.cache import cache
from django.core.paginator import EmptyPage, InvalidPage, Paginator
from django.http import Http404, HttpResponseNotAllowed, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import RedirectView, TemplateView, UpdateView, View

from prm.core.services import CacheService, MetamaskService
from prm.users.services import recalculate_user_balance, set_parent_in_smart

from .forms import AvatarUpdateForm, BuyTokenForm, ProfileUserUpdateForm

User = get_user_model()


def metamask_confirm(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            user = get_object_or_404(User, username=data.get("user"))
            account_address = data.get("accountAddress")
            signature = data.get("signature")
            csrf_token = data.get("csrf_token")
            # verify signature
            is_valid_signature = MetamaskService.verify_signature(
                account_address=account_address,
                signature=signature,
                original_message=csrf_token,
            )
            if not is_valid_signature:
                return JsonResponse({"error": "Invalid signature"}, status=400)
            # update user metamask data
            MetamaskService.confirm_user_wallet(
                user=user, account_address=account_address
            )

            if user.parent:
                set_parent_in_smart(user)
            recalculate_user_balance(user)
        except Exception as e:
            return JsonResponse({"message": "Error", "exception": str(e)}, status=500)
        return JsonResponse({"message": "Success"}, status=201)
    return HttpResponseNotAllowed(["POST"])


class PollToken(LoginRequiredMixin, TemplateView):
    def get_context_data(self, *args, **kwargs):
        token = CacheService.get_token()
        token_active_round = CacheService.get_token_active_round()
        token_rounds = CacheService.get_token_rounds()
        return {
            "token": token,
            "token_active_round": token_active_round,
            "token_rounds": token_rounds,
        }

    def get(self, request, *args, **kwargs):
        template_name = "dashboard/components/token_active_round.html"
        if request.path == reverse_lazy("dashboard:poll_token_rounds"):
            template_name = "dashboard/components/token_rounds.html"
        context = self.get_context_data()
        return render(request, template_name, context)


class PollUserBalance(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/components/user_balance.html"

    def get_context_data(self, *args, **kwargs):
        user = self.request.user
        token = CacheService.get_token()
        token_active_round = CacheService.get_token_active_round()
        user_balance = CacheService.get_user_balance(user, token)
        return {
            "user": user,
            "user_balance": user_balance,
            "token": token,
            "token_active_round": token_active_round,
        }


class PollUserTransactions(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/components/transaction_history.html"

    def get_context_data(self, *args, **kwargs):
        transactions = CacheService.get_user_transactions(self.request.user)
        return {"user_transactions": transactions}


class DashboardRedirectView(RedirectView):
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return reverse_lazy(
                "dashboard:index", kwargs={"username": self.request.user.username}
            )
        return reverse_lazy("account_login")


class DashboardBaseView(LoginRequiredMixin, View):
    template_name = ""
    default_limit = 10
    default_page = 1
    max_limit = 50

    def get_context_data(self):
        token = CacheService.get_token()
        token_rounds = CacheService.get_token_rounds()
        token_active_round = cache.get("token_active_round")
        user = self.request.user
        user_referral = self.request.build_absolute_uri(
            reverse_lazy("account_signup") + "?referral=" + user.username
        )
        user_balance = CacheService.get_user_balance(user, token)
        user_children = CacheService.get_user_children(user)
        user_transactions = CacheService.get_user_transactions(user)

        # Children pagination
        user_children = Paginator(
            user_children, self.request.COOKIES.get("children_size", self.default_limit)
        ).page(self.request.GET.get("c_page", self.default_page))
        user_children_page_range = user_children.paginator.get_elided_page_range(
            self.request.GET.get("c_page", self.default_page), on_each_side=3, on_ends=1
        )
        # Transactions pagination
        user_transactions = Paginator(
            user_transactions,
            self.request.COOKIES.get("transactions_size", self.default_limit),
        ).page(self.request.GET.get("t_page", self.default_page))
        user_transactions_page_range = (
            user_transactions.paginator.get_elided_page_range(
                self.request.GET.get("t_page", self.default_page),
                on_each_side=3,
                on_ends=1,
            )
        )

        return {
            "user": user,
            "user_referral_link": user_referral,
            "user_balance": user_balance,
            "user_children": user_children,
            "user_children_page_range": user_children_page_range,
            "user_transactions": user_transactions,
            "user_transactions_page_range": user_transactions_page_range,
            "token": token,
            "token_rounds": token_rounds,
            "token_active_round": token_active_round,
            "page_sizes": [10, 25, 50],
        }

    def get(self, request, *args, **kwargs):
        try:
            context = self.get_context_data()
        except (EmptyPage, InvalidPage):
            raise Http404()
        return render(request, self.template_name, context)


class DashboardIndexView(DashboardBaseView):
    template_name = "dashboard/index.html"


class DashboardTokenView(DashboardBaseView):
    template_name = "dashboard/token.html"

    def get(self, request, *args, **kwargs):
        context = self.get_context_data()
        context["buy_token_form"] = BuyTokenForm()
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = BuyTokenForm(request.POST)
        if form.is_valid():
            user = self.request.user
            return redirect(
                reverse_lazy("dashboard:token", kwargs={"username": user.username})
            )
        context = self.get_context_data()
        context["buy_token_form"] = form
        return render(request, self.template_name, context)


class DashboardTeamView(DashboardBaseView):
    template_name = "dashboard/team.html"


class DashboardProfileView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = ProfileUserUpdateForm
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "dashboard/profile.html"
    success_message = _("Информация успешно обновлена")

    def get_success_url(self):
        return reverse_lazy(
            "dashboard:profile", kwargs={"username": self.request.user.username}
        )

    def get_object(self, *args, **kwargs):
        return self.request.user


class AvatarUpdateView(LoginRequiredMixin, View):
    def post(self, request):
        form = AvatarUpdateForm(request.POST, request.FILES)
        if form.is_valid() and request.FILES:
            user = self.request.user
            user.avatar = form.cleaned_data.get("avatar")
            user.save()
            return JsonResponse({"avatar_url": user.avatar.url})
        # handle form errors
        errors = form.errors.as_data()
        error_messages = [
            error.message for error_list in errors.values() for error in error_list
        ]
        return JsonResponse({"error": error_messages}, status=400)

prm/users/views.py
from allauth.account.views import SignupView

from .forms import UserSignupForm


class UserSignupView(SignupView):
    form_class = UserSignupForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["request"] = self.request
        return kwargs

prm/templates/dashboard/index.html
{% extends "dashboard/base.html" %}

{% load static %}
{% load l10n %}
{% load i18n %}
{% load humanize %}

{% block inner_top %}
    {{ block.super }}
{% endblock inner_top %}

{% block inner_bot %}
<div class="big_tiles">
    <div id="defi" class="tile big_tile">
        <div class="defi_info">
            <h1 class="defi_name">DeFi Token PRM4ALL</h1>
            <p class="description">{% translate "Получай процент с товарооборота компании!" %}</p>
            <a href="{% url 'dashboard:token' username=user.username %}"><button class="btn btn-slim defi_btn">{% translate "Купить" %}</button></a>
        </div>
    </div>

    {% include 'dashboard/components/token_rounds.html' %}

    <div id="prm" class="tile big_tile">
        <div class="prm_text">
            <h3 class="big_name">Partner<br>Relationship<br>Management</h3>
            <p class="description">{% translate "Стань частью будущего!" %}</p>
            <div class="button_row">
                <button class="btn btn-slim">{% translate "Смотреть презентацию" %}</button>
                <button class="btn btn-slim">{% translate "Скачать PDF" %}</button>
            </div>
        </div>
    </div>
    <div id="video" class="tile big_tile">
        <div class="video_text">
            <h3 class="big_name">{% translate "Видео о проекте" %}</h3>
            <p class="description">{% translate "Революционное приложение для предпринимателей!" %}</p>
        </div>
        <iframe id="prm_video" src="https://www.youtube-nocookie.com/embed/M8Cqf67RZ44" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
    </div>
</div>
{% endblock inner_bot %}

prm/templates/dashboard/profile.html
{% extends "dashboard/base.html" %}

{% load static %}
{% load humanize %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %} - Profile{% endblock head_title %}
{% block crumbs_title %}Profile{% endblock crumbs_title %}
{% block page_title %}Profile{% endblock page_title %}

{% block inner_top %}
<div class="profile_tiles">
    <div class="profile_tile tile">
        <div class="profile_info">
            <div class="avatar">
                <img class="avatar-img avatar_pic" src="{{ user.avatar.url }}" alt="Avatar">
                <img id="avatar-select" class="avatar_change" src="{% static 'img/icons/change_img.svg' %}" alt="Change avatar">
            </div>
            <div class="profile_text">
                <p class="name">{{ user.first_name }} {{ user.last_name }}</p>
                <p class="registration_date description">
                    {% translate "Дата регистрации" %}: {{ user.date_joined|date:"d.m.Y" }}
                </p>
            </div>
            <div class="profile_nums">
                <div id="profile_token_amount" class="profile_amount">
                    <p class="profile_counter">{{ user.token_balance|intcomma }}</p>
                    <p class="description">{% translate "Всего токенов" %}</p>
                </div>
                <div class="profile_amount">
                    <p class="profile_counter">{{ user.children.count }}</p>
                    <p class="description">{% translate "Приглашенных" %}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="investor_tile tile">
        <h3 class="invite_text">
            {% translate "Пригласи инвестора в проект<br> и получи 5% в токенах!" %}
        </h3>

    </div>
</div>
{% endblock inner_top %}

{% block inner_bot %}
<div id="settings" class="full_tile tile">
    <div class="settings_text">
        <h3 class="big_name">{% translate "Редактировать профиль" %}</h3>
    </div >
    <form id="avatar-form" method="POST" enctype="multipart/form-data" action="{% url 'dashboard:avatar_update' %}">
        {% csrf_token %}
        <input type="file" name="avatar" id="avatar-input" style="display: none;" onchange="handleAvatarSelect()">
        <div id="error-block" class="alert-error"></div>
    </form>
    <form id="profile-form" class="form settings_table" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="settings_btn_bar">
            {% if not user.metamask_confirmed %}
            <button id="settings_metamask_btn" class="btn btn-slim-wide">
                {% translate "Подтвердить metamask" %}
            </button>
            {% endif %}
            <button id="settings_save_btn" class="btn btn-slim-wide" type="submit">
                {% translate "Сохранить" %}
            </button>
        </div>
    </form>
</div>
{% endblock inner_bot %}


{% block inline_javascript %}
<script defer src="{% static 'js/avatar-update.js' %}"></script>

{% if not user.metamask_confirmed %}
<script defer src="https://cdn.ethers.io/lib/ethers-5.2.umd.min.js" type="application/javascript"></script>
<script>
    function metamaskConfirm() {
        try {
            window.ethereum.request({ method: 'eth_requestAccounts' }).then(function () {
                provider = new ethers.providers.Web3Provider(window.ethereum);
                provider.getNetwork().then(function (result) {
                    provider.listAccounts().then(function (result) {
                        accountAddress = result[0];
                        signer = provider.getSigner();
                        signer.signMessage("{{ csrf_token }}").then((signature) => {
                            // Send POST request
                            fetch("{% url 'dashboard:metamask_confirm' %}", {
                                method: 'POST',
                                headers: {
                                    'Content-Type': 'application/json',
                                    'X-CSRFToken': "{{ csrf_token }}",
                                },
                                body: JSON.stringify({
                                    user: '{{ user.username }}',
                                    accountAddress: accountAddress,
                                    signature: signature,
                                    csrf_token: "{{ csrf_token }}"
                                })
                            }).then(function (response) {
                                window.location.href = "{% url 'dashboard:profile' user.username %}";
                            });
                        })
                    });
                });
            }).catch(error => {
                console.log(error)
            });
        } catch {
            alert('Пожалуйста установите MetaMask приложение для вашего браузера.');
        }
    }

    document.getElementById("settings_metamask_btn").addEventListener("click", (event) => {
        event.preventDefault();
        metamaskConfirm();
    });
</script>
{% endif %}

{% endblock inline_javascript %}

prm/templates/dashboard/team.html
{% extends "dashboard/base.html" %}

{% load humanize %}
{% load i18n %}
{% load dashboard_extras %}

{% block head_title %} - Team{% endblock head_title %}
{% block crumbs_title %}Team{% endblock crumbs_title %}
{% block page_title %}Team{% endblock page_title %}

{% block inner_top %}
    {{ block.super }}
{% endblock inner_top %}

{% block inner_bot %}
<section class="tile tile-lg">
    <h2 class="big_name">{% translate "Моя команда" %}</h2>
    <div class="flexible-table">
        <div class="row row-header">
            <div class="cell">{% translate "ФИО" %}</div>
            <div class="cell">{% translate "Логин" %}</div>
            <div class="cell">{% translate "Телефон" %}</div>
            <div class="cell">{% translate "Кол-во купленных токенов" %}</div>
            <div class="cell">{% translate "Дата регистрации" %}</div>
            <div class="cell">{% translate "Город" %}</div>
        </div>
        {% for user in user_children %}
            <div class="row">
                <div class="cell">{{ user.full_name }}</div>
                <div class="cell">{{ user.username }}</div>
                <div class="cell">{{ user.phone_number|clean_phone_number }}</div>
                <div class="cell">{{ user.token_balance|intcomma }}</div>
                <div class="cell">{{ user.date_joined|date:"d.b.Y" }}</div>
                <div class="cell">{{ user.settings.city }}</div>
            </div>
        {% endfor %}
    </div>
    <div class="pages">
        <select id="children_size" class="page_amount_selector">
            {% for amount in page_sizes %}
                <option value="{{ amount }}" {% if amount == user_children.paginator.per_page %}selected{% endif %}>
                    Показывать по {{ amount }} записей
                </option>
            {% endfor %}
        </select>
        <ul class="pagination">
            {% if user_children.has_previous %}
                <li>
                    <a class="page_btn" href="?page={{ user_children.previous_page_number }}">
                        &lt;
                    </a>
                </li>
                {% else %}
                <li><span class="page_btn" disabled>&lt;</span></li>
            {% endif %}
            {% for page_num in user_children_page_range %}
                {% if page_num == user_children.number %}
                    <li><span class="page_btn active_page">{{ page_num }}</li>
                {% elif page_num == user_children.paginator.ELLIPSIS %}
                    <li><span class="page_btn">{{ page_num }}</li>
                {% else %}
                    <li><a class="page_btn" href="?c_page={{ page_num }}">{{ page_num }}</a></li>
                {% endif %}
            {% endfor %}

            {% if user_children.has_next %}
                <li>
                    <a class="page_btn" href="?c_page={{ user_children.next_page_number }}">
                        &gt;
                    </a>
                </li>
                {% else %}
                <li><span class="page_btn">&gt;</span></li>
            {% endif %}
        </ul>
    </div>
</section>

{% include "dashboard/components/transaction_history.html" %}

{% endblock inner_bot %}

prm/templates/dashboard/token.html
{% extends "dashboard/base.html" %}

{% load static %}
{% load humanize %}
{% load l10n %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load dashboard_extras %}

{% block head_title %} - Token{% endblock head_title %}
{% block crumbs_title %}Token{% endblock crumbs_title %}
{% block page_title %}Token{% endblock page_title %}

{% block inner_top %}
    {{ block.super }}
{% endblock inner_top %}

{% block inner_bot %}
<div id="big_tiles_2" class="big_tiles">
    <div id="round" class="big_tile tile">
        <h3 class="big_name">{% translate "Покупай токены PRM и зарабатывай вместе с нами" %}</h3>

        {% include 'dashboard/components/token_active_round.html' %}

        <form class="form-slim buy-token-form" method="POST">
            {% csrf_token %}
            {{ buy_token_form|crispy }}
            <input type="hidden" value="{{ token_active_round.unit_price|unlocalize }}" name="current_token_price" id="current_token_price">
            <p class="grey_text" id="buy_token_description">Сеть BNB Smart Chain (BEP20).  Минимальная сумма покупки 1000 USDT.<br>Среднее время зачисления 5 мин. Добавьте токены PRM в MetaMask.</p>
            <button id="buyButton" class="btn btn-slim" type="button">{% translate "Купить" %}</button>
        </form>
        

    </div>

    {% include 'dashboard/components/token_rounds.html' %}

</div>

{% include "dashboard/components/transaction_history.html" %}

{% endblock inner_bot %}


{% block inline_javascript %}
<script type="text/javascript"> 
    window.METAMASK_ADDRESS = "{{user.metamask_wallet}}";
 </script> 
<script src="{% static "js/smart-logic.js" %}"></script>
<script src="{% static "js/token-buy-form.js" %}"></script>
{% endblock inline_javascript %}